# Generated by Django 6.1 on 2026-08-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee Payment'), ('POLICE', 'Police Payment'), ('FUEL', 'Fuel'), ('OTHER', 'Other Expense')], max_length=20),
        ),
    ]
