# Generated by Django 6.1 on 2026-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('ELECTRICITY', 'Electricity'), ('RENT', 'Rent'), ('POLICE', 'Police'), ('OTHERS', 'Others'), ('MAINTENANCE', 'Maintenance')], max_length=20),
        ),
    ]
