# Generated by Django 6.1 on 2026-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyearning',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='dailyearning',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('ELECTRICITY', 'Electricity'), ('RENT', 'Rent'), ('POLICE', 'Police'), ('FUEL', 'Fuel'), ('MAINTENANCE', 'Maintenance'), ('OTHERS', 'Others')], max_length=20),
        ),
    ]
