# Generated by Django 6.1 on 2026-08-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_dailyearning_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee Payment'), ('POLICE', 'Police Payment'), ('FUEL', 'Fuel'), ('ELECTRICITY', 'Electricity'), ('RENT', 'Rent'), ('MAINTENANCE', 'Maintenance'), ('OTHERS', 'Other Expense')], max_length=20),
        ),
    ]
