# Generated by Django 6.1 on 2026-09-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('coins_collected', models.PositiveIntegerField(help_text='Number of coins physically removed from the pool tables.')),
                ('coin_value', models.DecimalField(decimal_places=2, default=20.0, help_text='Value of one pool game/coin in KSh.', max_digits=8)),
                ('actual_m_pesa', models.DecimalField(blank=True, decimal_places=2, help_text='Actual M-Pesa amount received for this collection.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
    ]
