# Generated by Django 6.1 on 2026-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_coincollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coincollection',
            name='coin_value',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Value of one coin in KSh.', max_digits=8),
        ),
    ]
