# Generated by Django 6.1 on 2026-09-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_make_business_data_user_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincollection',
            name='additional_coins',
            field=models.PositiveIntegerField(default=0, help_text='Additional coins found or collected outside the main collection.'),
        ),
        migrations.AddField(
            model_name='coincollection',
            name='lost_coins',
            field=models.PositiveIntegerField(default=0, help_text='Coins lost, missing, or otherwise unaccounted for.'),
        ),
    ]
